Update README.md
kobotoolbox/kobocat pull request #669
Opened 2021-01-21 22:37 UTC by JacquelineMorrissette

Updated the README.md to include the steps to run the tests in the KoBoCat container to limit time spent troubleshooting for anyone who may not be too familiar with the code.

2021-01-28 15:14 UTC, noliveleger requested changes

2021-01-28 15:14 UTC, noliveleger commented on README.md
> +$ pip insall -r requirements/dev.pip
typo: `install`

2021-01-28 15:14 UTC, noliveleger commented on README.md
> +$ docker exec -it {{kobocat container}} /bin/bash
You could add command with kobo-install too. (i.e. `For kobo-install users `./run.py -cf exec kobocat bash`)

2021-01-29 02:08 UTC, JacquelineMorrissette reviewed
@noliveleger I made both the changes you suggested. How does it look now?

2021-01-29 14:36 UTC, noliveleger commented on README.md
> +For Kobo-Install Users, enter the folder for Kobo-Install and run this command
I think the correct way is `KoBoCAT` (see https://github.com/kobotoolbox/kobocat/blob/master/README.md) 
I used to write KoBo-Install, but we decided to change to `kobo-install` (https://github.com/kobotoolbox/kobo-install/commit/b4da7d7415af60ab2c299f1a4aeb011b76b5dcaa) to match with `kobo-docker`

It's not an error at all but I think it's better to be consistent in every repo. What do you think?

2021-02-18 21:59 UTC, noliveleger approved these changes

2021-02-18 21:59 UTC, merged