Changed how the default database URL is read
kobotoolbox/kobocat pull request #812
Opened 2022-04-26 14:40 UTC by JacquelineMorrissette

## Description
Changed the default database to read from `KC_DATABASE_URL` and fallback to `DATABASE_URL`

## Related Issues
closes #804

2022-04-27 20:18 UTC, noliveleger requested changes

2022-04-27 20:18 UTC, noliveleger commented on onadata/settings/base.py
> +if 'KPI_DATABASE_URL' in env.ENVIRON:
You meant `KC_DATABASE_URL`?  😄

2022-04-27 20:18 UTC, noliveleger commented on onadata/settings/base.py
> +    DATABASES['default'] = env.db_url(default='KC_DATABASE_URL')
I think the syntax should be `env.db_url('KC_DATABASE_URL', default="sqlite:///%s/db.sqlite3" % PROJECT_ROOT)`

2022-04-27 20:18 UTC, noliveleger commented on onadata/settings/base.py
> +    DATABASES['default'] = env.db_url(default='KC_DATABASE_URL')
I think the syntax would be `env.db_url('KC_DATABASE_URL', default="sqlite:///%s/db.sqlite3" % PROJECT_ROOT)`

2022-04-27 20:18 UTC, noliveleger commented on onadata/settings/base.py
> +    DATABASES['default'] = env.db_url(default='DATABASE_URL')
I think the syntax should be `env.db_url('DATABASE_URL', default="sqlite:///%s/db.sqlite3" % PROJECT_ROOT)`.

2022-04-27 20:18 UTC, noliveleger commented on onadata/settings/base.py
> +    DATABASES['default'] = env.db_url(default='DATABASE_URL')
I think the syntax should be `env.db_url('DATABASE_URL', default="sqlite:///%s/db.sqlite3" % PROJECT_ROOT)`.

2022-05-17 00:14 UTC, jnm commented
I could use this in my local development environment right now :grin:

I think the "fall back" part may be absent from the latest revisions?

> Read from `KC_DATABASE_URL` and fall back to DATABASE_URL if it's not present.

2022-05-17 13:14 UTC, noliveleger commented
> I could use this in my local development environment right now 😁
> 
> I think the "fall back" part may be absent from the latest revisions? From the description of #804:
> 
> > Read from `KC_DATABASE_URL` and fall back to DATABASE_URL if it's not present.

Indeed.

2022-05-27 05:02 UTC, jnm approved these changes

2022-05-27 05:02 UTC, merged