Create daily and monthly xform submission counter models
kobotoolbox/kobocat pull request #836
Opened 2022-07-20 16:14 UTC by JacquelineMorrissette

## Description
Created DailyXFormSubmissionCounter and MonthlyXFormSubmissionCounter models to improve the request speed for form statistics

2022-08-01 22:04 UTC, jnm requested changes

2022-08-01 22:04 UTC, jnm commented on onadata/apps/logger/tests/models/test_xform_submission_counters.py
> +    def test_delete_daily_counters(self, daily_counts):
it seems like `daily_counts`, which comes from the `patch()`, doesn't get used for anything

2022-08-01 22:04 UTC, jnm commented on onadata/libs/utils/logger_tools.py
>          update_user_submissions_counter(instance=instance, created=True)
this and its associated `SubmissionCounter` model could be removed per https://hackmd.io/_c5ylWuEQ6anJcMAj0odyQ#Questions

2022-09-02 00:20 UTC, noliveleger approved these changes
LGTM, @jnm you already reviewed the PR and your requests have been applied.
I'm merging the branch to make it easy for service usage endpoint.

2022-09-02 00:20 UTC, merged