WIP - Trash bin
kobotoolbox/kobocat pull request #871
Opened 2023-03-22 19:24 UTC by noliveleger

2023-03-22 20:21 UTC, jnm reviewed
Initial read-through while still in progress. Looking good :+1:

2023-03-22 20:21 UTC, jnm commented on onadata/apps/logger/models/xform.py
> +    pending_delete = LazyDefaultBooleanField(default=False)
Apparently we no longer need this lazy-field stuff starting with [PostgreSQL 11](https://www.postgresql.org/docs/11/sql-altertable.html) :tada:

2023-03-22 20:21 UTC, jnm commented on onadata/apps/logger/models/xform.py
> +        return super(models.Manager, self).get_queryset()
`pass` :blush:

2023-03-31 15:00 UTC, noliveleger commented on onadata/apps/main/migrations/0011_drop_old_kpi_tables.py
> +def get_operations():
As per our discussion, we did improve the migration by dropping the constraints first and drop tables.

2023-03-31 19:49 UTC, jnm requested changes

2023-03-31 19:49 UTC, jnm commented on onadata/apps/api/tests/viewsets/test_xform_viewset.py
> +        Test that bob (or anyone else) has access to bob's pending delete XForm
"does not have access"?

2023-03-31 19:49 UTC, jnm commented on onadata/apps/api/viewsets/xform_viewset.py
> +        rmdir(f'{username}/attachments/{xform_uuid}')
maybe excessively paranoid, but can we add a check to make sure the UUID and `id_string` are not empty before calling `rmdir()`?

2023-03-31 20:19 UTC, noliveleger commented on onadata/apps/api/tests/viewsets/test_xform_viewset.py
> +        Test that bob (or anyone else) has access to bob's pending delete XForm
Yep, I wanted to say "no access" .

2023-04-05 16:19 UTC, merged